services:

  hpts:
    image: ghcr.io/zveronline/http-proxy-to-socks:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8080:8080"
    command: -s tpws:1080 -l 0.0.0.0 -p 8080
    networks:
      - antidpi

  tpws:
    image: ghcr.io/zveronline/zapret-docker:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "1080:1080"
    command: --port=1080 --socks --tlsrec=sni --disorder
    networks:
      - antidpi

networks:
  antidpi:
    driver: overlay
    attachable: true
